name: CI/CD Pipeline - Math Score Predictor

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Login to Docker Hub
      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build & Push Docker Image
      - name: Build and Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/math-score-predictor:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/math-score-predictor:latest

      # Deploy on EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/math-score-predictor:latest
            docker stop math-app || true
            docker rm math-app || true
            docker run -d -p 5000:5000 --name math-app ${{ secrets.DOCKER_USERNAME }}/math-score-predictor:latest
