#name: CI/CD Math Score Predictor
#
#on:
#  push:
#    branches: [main]
#
#jobs:
#  ci:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Setup Python
#        uses: actions/setup-python@v4
#        with:
#          python-version: '3.10'
#
#      - name: Install dependencies
#        run: pip install -r requirements.txt
#
#      - name: Run tests
#        run: python -m pytest tests/
#
#  cd:
#    needs: ci
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Log into DockerHub
#        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
#
#      - name: Build Docker image
#        run: docker build -t srinu0930/math-score-predictor:latest .
#
#      - name: Push Docker image
#        run: docker push srinu0930/math-score-predictor:latest
#
#      - name: Deploy on server via SSH
#        uses: appleboy/ssh-action@v0.1.10
#        with:
#          host: ${{ secrets.SERVER_HOST }}
#          username: ${{ secrets.SERVER_USER }}
#          key: ${{ secrets.SERVER_SSH_KEY }}
#          script: |
#            docker pull srinu0930/math-score-predictor:latest
#            docker stop ml-app || true
#            docker rm ml-app || true
#            docker run -d -p 5000:5000 --name ml-app srinu0930/math-score-predictor:latest
#
#


name: CI/CD Math Score Predictor

on:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v3

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install dependencies
      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements.txt

      # Run tests
      - name: Run tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          python -m pytest tests/

  cd:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v3

      # Log in to DockerHub
      - name: Log into DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build Docker image with Git commit SHA tag
      - name: Build Docker image
        run: docker build -t srinu0930/math-score-predictor:${{ github.sha }} -t srinu0930/math-score-predictor:latest .

      # Push Docker image
      - name: Push Docker image
        run: docker push srinu0930/math-score-predictor:${{ github.sha }}

      - name: Push latest tag
        run: docker push srinu0930/math-score-predictor:latest

      # Deploy to AWS EC2 via SSH
      - name: Deploy on AWS EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull srinu0930/math-score-predictor:latest
            docker stop ml-app || true
            docker rm ml-app || true
            docker run -d -p 5000:5000 --name ml-app srinu0930/math-score-predictor:latest
